name: AnonfilesUpload  
on:
  
  workflow_dispatch:
    inputs:
      Directlink:
        description: 'Enter DirectLink To Download ⚡️'
        required: true
      Filename:
        description: 'Enter FIle name '
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Directlink
        run: wget ${{ github.event.inputs.Directlink }}

      - name: Upload 
        run: |
             curl -F "file=@RedTeamOperatorMalwareDevelopmentEssentialshide01.ir.tar.gz" https://api.anonfiles.com/upload?token=70826d8e7bab83c6 

          
         
  
        
