name: my workflow
on: 
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
             echo $(date +%Y-%m-%d) >date.txt
             echo "GITHUB_DATE=$(echo "$(<date.txt )")" >> $GITHUB_ENV
    - name: Test
      run: echo ${{env.GITHUB_DATE}}
