name: Megauploadtest  
on:
  
  workflow_dispatch:
    inputs:
      Directlink:
        description: 'Enter DirectLink To Download ⚡️'
        required: true
      Filename:
        description: 'Enter FIle name '
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Directlink
        run: wget ${{ github.event.inputs.Directlink }}

      - name: Upload 
        uses: Difegue/action-megacmd@master
        with:
          args: put /github/workspace/creambd.csv
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          
         
  
        
