name: telegram message
on: 
  watch:
    types: [started]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on star
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            #sᴛᴀʀ ʜᴜᴇʜᴜᴇ
            
            https://github.com/${{ github.actor }} Sᴛᴀʀʀᴇᴅ Rᴇᴘᴏ Mᴜʟᴛɪᴄʟᴏᴜᴅ-Uᴘʟᴏᴀᴅ
            
            tag: ${{ env.NOW }}
            
            env:
          NOW: $(date +'%Y-%m-%dT%H:%M:%S')
            

            
            
            
