name: telegram message
on: 
  watch:
    types: [started]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on star
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            #Star huehue
            ❤️Github Notifcation
            ${{ github.actor }} Forked Repo Multicloud-Upload:
            star msg: ${{ github.event.started[0].message }}
            
            
            
            
