name: starnotify
on:
 workflow_dispatch:
 watch:
    types: [started]

  
  #kindevilsorg
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      date: $(date +'%Y-%m-%d')
      
      
      
#kindevilsorg
    steps:
      - uses: actions/checkout@v3
#kindevilsorg
      - name: echoing time
        run: |
              echo ${{ env.date}} >date.txt
              cat date.txt
              
              env:
               datetxt: cat date.txt
      
  
      - name: send telegram message on star
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            #sᴛᴀʀ ʜᴜᴇʜᴜᴇ
            
             ${{ env.datetxt}}
            
            
            https://github.com/${{ github.actor }} Sᴛᴀʀʀᴇᴅ Rᴇᴘᴏ Mᴜʟᴛɪᴄʟᴏᴜᴅ-Uᴘʟᴏᴀᴅ

        
