name: telegram message
on: 
  watch:
    types: [started]

jobs:

job1:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on star
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            #sᴛᴀʀ ʜᴜᴇʜᴜᴇ
            
            https://github.com/${{ github.actor }} Sᴛᴀʀʀᴇᴅ Rᴇᴘᴏ Mᴜʟᴛɪᴄʟᴏᴜᴅ-Uᴘʟᴏᴀᴅ
            
            
  job2:
       needs: job1
        steps:
         - name: Get current time
           uses: josStorer/get-current-time@v2.0.2
           id: current-time
              with: 
                  format: YYYYMMDD-HH
                   utcOffset: "+08:00"
  - name: Use current time
    env:
      TIME: "${{ steps.current-time.outputs.time }}"
      R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      YEAR: "${{ steps.current-time.outputs.year }}"
      DAY: "${{ steps.current-time.outputs.day }}"
    run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
            
            
            
            
