name: MultiCloudupload  
on:
  #kindevilsorg
  workflow_dispatch:
  #kindevilsorg
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      date: $(date +'%Y-%m-%d')
#kindevilsorg
    steps:
      - uses: actions/checkout@v3
#kindevilsorg
      - name: echoing time
        run: |
              echo ${{ env.date}} >date.txt
              cat date.txt
        
