name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
             echo $(date +%Y-%m-%d) >date.txt
             echo "GITHUB_SHA_SHORT=$(echo echo "$(<date.txt )")" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
